server:
  port: 8101

spring:
  application:
    name: bookserver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.43.63.185:3306/cloudstudy
    username: root
    password: Dt7626761Wamm@@
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  cloud:
    nacos:
      discovery:
        # Nacos注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8858

#开启日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-prefix: db_

seata:
  service:
    grouplist:
      default: localhost:8868
    vgroup-mapping:
      bookserver-seata-service-group: default